config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  authenticate :user, lambda {|u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end  
  use_doorkeeper
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :questions  do
    resources :comments, shallow: true,  defaults: { commentable: "question" }
    resources :answers, shallow: true do
      resources :comments, shallow: true, defaults: { commentable: "answer" }
    end
    resource :subscription, only: [:create, :destroy]
  end

  namespace :api do
    namespace :v1 do
     resources :profiles, only: [:index] do
      get :me, on: :collection 
     end
     resources :questions do 
        resources :answers, shallow: true
     end   
    end  
  end

  root to: "questions#index"
  
  get "users/add_email_form", to: "users#add_email_form", as: :add_email_form
  post "users/add_email", to: "users#add_email", as: :add_user_email

  get "search/", to: "search#index", as: :search
  get '/answers/new(.:format)', to: 'answers#new', as: 'new_answer'
#  get '/users/sign_up(.:format)', to: 'devise/registrations#new', as: 'new_user'
 mount ActionCable.server => '/cable'
end

app/models/question.rb
#class Question < ApplicationRecord
class Question < ActiveRecord::Base
    validates :title, :body, presence: true
    has_many :answers, dependent: :destroy

    has_many :attachments, as: :attachmentable
    accepts_nested_attributes_for :attachments, allow_destroy: true

    has_many :comments, as: :commentable

    has_many :subscriptions, dependent: :destroy
    has_many :subscribed_users, through: :subscriptions, source: :user

  #  accepts_nested_attributes_for :comments, allow_destroy: true

    belongs_to :user

    after_create :subscription_for_author

    scope :last_day_questions, -> { where('created_at > ?', 24.hours.ago ) }

  
    private

     def subscription_for_author
       self.subscriptions.create(user: user)
     end    
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  before_action :find_question, only: [:show]


   def index
     # render nothing: true
     # head: :ok
     # @questions = Question.all
      @questions = Question.order(:id)
     # respond_with @questions.to_json(include: :answers) 
     respond_with @questions   # с сериалайзером
   end

   def show
    respond_with @question, serializer: ::DetailedQuestionSerializer
  end

  def create
    respond_with( @question = Question.create(question_params.merge(user_id: current_resource_owner.id)))
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def find_question
    @question = Question.find(params[:id])
  end

end    

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :load_question, only: [:show, :edit, :update, :destroy, :subscribe, :unsubscribe]
    after_action  :publish_question, only: [:create]
    
    respond_to :html #11 zan

    # authorize_resource #CanCan
    #load_and_authorize_resource #CanCan

    def index
      authorize Question

      #authorize! :index, Question #CanCan
      #authorize! :read, Question #CanCan

        # @questions = Question.all
        respond_with(@questions = Question.all)
    end

    def show
      authorize @question
      #authorize! :read, @question #(обьект) #CanCan
      #@answer = @question.answers.build
      @answer = Answer.new(question_id: @question.id)
      # не корректно @comment = Comment.new(question_id: @question.id, user_id: current_user.id)
      
      #@comment = Comment.new
      #@comment.user_id = current_user.id
      #@comment.commentable_type = 'Question'
      #@comment.commentable_id = @question.id

      @answer.attachments.build
      @answer.comments.build
      @comment = @question.comments.new(user_id: current_user&.id)
      respond_with @question
    end

    def new
      #authorize! :create, Question #CanCan
        @question = Question.new
        @question.attachments.build
        @question.comments.build
        
        authorize @question
        respond_with @question
    end

    def edit
      authorize @question
      @attachments = @question.attachments 
      @comments = @question.comments 
    end

    def create
      @question = Question.new(question_params)
      @question.user_id = current_user.id

      authorize @question
      flash.notice = "Your question successfully created." if  @question.save
      respond_with @question
      # binding.pry
      # redirect_to @question
      # redirect_to action: :index
      # flash.now.notice = "Your question successfully created."
      # render :new  
    end

    def update
      authorize @question
      @question.update(question_params)
      @attachments = @question.attachments
      @comments    = @question.comments
      respond_with @question
      # @attachments.each { |att|  puts(att.file, att.id) }
    end

    def destroy
      authorize @question
      # authorize! :destroy, @question #(обьект удалит любые) #CanCan
      # authorize! :destroy, Question #(обьект удалит только свои) #CanCan
      respond_with(@question.destroy) if @question.user_id == current_user.id
      flash.notice = "У Вас нет прав на удаление этой записи" if @question.user_id != current_user.id
      #redirect_to action: :index
    end

  
    private
    def load_question
        @question = Question.find(params[:id])
    end

    def publish_question
       return if @question.errors.any?
       #ActionCable.server.broadcast('questions',  {text: 'new question' })
  
       ActionCable.server.broadcast(
        'questions', 
        ApplicationController.render(
          partial: 'questions/question_row',
          locals: { question: @question, current_user: current_user }
        )
      )
    end  

    def question_params
        params.require(:question).permit(:title, :body, 
        attachments_attributes: 
        [  :file, :attachmentable_id, 
        :attachmentable_type, :_destroy, :id],
        comments_attributes: 
        [  :strComment, :commentable_id, 
          :commentable_type, :_destroy, :id])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer111.html.slim
  tr class="answer_row_#{answer.id}"
    td = answer.body
    - if answer.best
      td = 'Лучший'
    - else
      td = ' '
    td = link_to "Показать", answer_path(answer)
    -if (user_signed_in?)  && (current_user.id == answer.user_id)
      td = link_to "Удалить", answer_path(answer), method: :delete, data: { confirm: "Удалить?" }
    - if answer.persisted?  
      -if (user_signed_in?) && (current_user.id == answer.user_id) 
        td 
          =link_to "Редактировать", '', class: 'edit-answer-link', data: {answer_id: answer.id}
        td.answers_edit
          =form_for(answer, url: answer_path(answer, format: :js),  method: :patch, remote: true, html: { id: "edit-answer-#{answer.id }" }) do |f| 
            =f.label(:body, "Ответ")
            =f.text_area :body 
            =f.label(:best, "Лучший")
            =f.check_box(:best, {}, "True", "False")

            =>f.submit "Сохранить", class: "btn btn-primary answer_btn_#{answer.id}"
            =link_to "Отмена", '', 
                 class: "cancel_form_link  btn-primary right_btn btn btn-default"

app/views/questions/_answer_row.html.slim
  tr  class="answer_row_#{answer.id}" 
    td 
      ul  style="list-style: none; "
        - answer.attachments.each do |a|
          li = link_to a.file.identifier, a.file.url 

    td id = 'answerBody' style = "padding-left: 10px; padding-right: 10px;" = answer.body
    - if answer.best
      td  style = "padding-right: 10px;" = 'Лучший'
    - else
      td  style = "padding-right: 10px;" = ' '
    td  style = "padding-right: 10px;" = link_to "Показать", answer_path(answer),  class: 'show-answer-link'
 
    /-if (user_signed_in?)  && (current_user.id == answer.user_id)

    -if (current_user)  && (current_user.id == answer.user_id)
      td  style = "padding-right: 10px;" = link_to "Удалить", answer_path(answer),  class: 'del-answer-link', method: :delete, remote: true, data: {answer_id: answer.id,  confirm: 'Удалить?' }
    - if answer.persisted?  
      /-if (user_signed_in?) && (current_user.id == answer.user_id) 

      -if (current_user) && (current_user.id == answer.user_id) 
        td  style = "padding-right: 10px;"
          =link_to "Редактировать", '', class: 'edit-answer-link', data: {answer_id: answer.id}
        td.answers_edit
          /- remote_sign = answer.count > 0 ? true : false
          /- format_sign = answer.count > 0 ? :json : :html
          /=form_for(answer, url: answer_path(answer, format: format_sign),  method: :patch, remote: remote_sign, html: { id: "edit-answer-#{answer.id }" }) do |f| 
          =form_for(answer, url: answer_path(answer, format: :json),  method: :patch, remote: true, html: { id: "edit-answer-#{answer.id }" }) do |f| 
            .row
              .col-md-2

                =f.label(:body, "Ответ")
                =f.text_area :body 
                =>f.label(:best, "Лучший")
                =>f.check_box(:best, {}, "true", "false")
                
            .row.col-md-2 Attachments:
            br
            .row
              .col-md-0
                = f.fields_for :attachments do |a|
                  = render 'questions/attachment_fields', f: a
              .col-md-10= link_to_add_association "Добавить", f, :attachments, partial: 'questions/attachment_fields'

            .row
              .col-md-0
                =>f.submit "Сохранить", class: "answer_btn_#{answer.id} btn btn-primary"
                = link_to "Отмена", '', class: "cancel_form_link  btn-primary right_btn btn btn-default"

  template id="task-template"
    tr  class="answer_row_#{answer.id} answer_row_temp" 
      td 
        ul  style="list-style: none; "
          - answer.attachments.each do |a|
            li.answerFile = link_to a.file.identifier, a.file.url 

      td id = 'answerBody' style = "padding-left: 10px; padding-right: 10px;" = answer.body
      - if answer.best
        td id ='answerBest'  style = "padding-right: 10px;" = 'Лучший'
      - else
        td id ='answerBest'  style = "padding-right: 10px;" = ' '
      td  style = "padding-right: 10px;" = link_to "Показать", answer_path(answer),  class: 'show-answer-link'
      -if (current_user)  && (current_user.id == answer.user_id)
        td  style = "padding-right: 10px;" = link_to "Удалить", answer_path(answer),  class: 'del-answer-link', method: :delete, remote: true, data: {answer_id: answer.id,  confirm: 'Удалить?' }
      - if answer.persisted?  
        -if (current_user) && (current_user.id == answer.user_id) 
          td  style = "padding-right: 10px;"
            =link_to "Редактировать", '', class: 'edit-answer-link', data: {answer_id: answer.id}
          td.answers_edit
            
            =form_for(answer, url: answer_path(answer, format: :json),  method: :patch, remote: true, html: { id: "edit-answer-#{answer.id }" }) do |f|   
              .row
                .col-md-2

                  =f.label(:body, "Ответ")
                  =f.text_area :body 
                  =>f.label(:best, "Лучший")
                  =>f.check_box(:best, {}, "true", "false")
                  
              .row.col-md-2 Attachments:
              br
              .row
                .col-md-0
                  = f.fields_for :attachments do |a|
                    = render 'questions/attachment_fields', f: a
                .col-md-10= link_to_add_association "Добавить", f, :attachments, partial: 'questions/attachment_fields'

              .row
                .col-md-0
                  =>f.submit "Сохранить", class: "answer_btn_#{answer.id} btn btn-primary"
                  = link_to "Отмена", '', class: "cancel_form_link  btn-primary right_btn btn btn-default"

app/views/questions/_attachment_field_edit.html.slim
.row

.stroka_faila
  .nested-fields
    .field
      .row
      .col-md-1 => f.label :file 
      .col-md-2 => link_to_remove_association 'Удалить', f
      .col-md-4 => f.file_field  :file, type: "hidden"
      .col-md-4 => link_to f.object.file.identifier, f.object.file.url
/      .col-md-4 => f.text_field  :filet, value: f.object.file.identifier

app/views/questions/_attachment_fieldp.html.slim
.row
.stroka_faila
  .nested-fields
    .field
      .row
      .col-md-1 => f.label :file
      .col-md-2 => link_to_remove_association 'Удалить', f
      .col-md-4 => f.file_field  :file 
      .col-md-4 => f.text_field  :filet, value: f.object.file.identifier

app/views/questions/_attachment_fields.html.slim
.row
.stroka_faila
  .nested-fields
    .field
      .row
      .col-md-1 => f.label :file
      .col-md-2 => link_to_remove_association 'Удалить', f
      .col-md-4 => f.file_field  :file||f.object.file.identifier
      - if f.object.file.present?
        .col-md-4 = f.object.file.identifier 
       

      
        

app/views/questions/_comment_fields.html.slim
.row
.stroka_comment
  .nested-fields
    .field
      .row
      .col-md-1 => f.label :strComment
      .col-md-2 => link_to_remove_association 'Удалить', f
      .col-md-4 => f.file_field  :strComment

app/views/questions/_comment_row.html.slim
- email = comment.user.email

.flex_row
  .comment_element => email
  .comment_element => comment.strComment
  
  -if current_user && (current_user.id == comment.user_id)
    .comment_element => link_to "Удалить" , comment_path(id: comment.id), method: :delete, data: { confirm: "Удалить?", comment_udal_id: "#{comment.id}" },  id: "del-comment-#{comment.id }", class: 'del-comment-link' 
    .comment_element
      a href="#" class='edit-comment-link' data-comment-id="#{comment.id}" Редактировать
   
      
      =form_for(comment, url: comment_path(id: comment.id),  method: :patch, html: { id: "edit-comment-#{comment.id }", class: "comment_edit" }) do |f| 
        .row
          .col-md-0
            =f.label(:strComment, "Комментарий")
            =f.text_area :strComment 
        .row
          .col-md-0
            =>f.submit "Сохранить", class: "comment_btn_#{comment.id} btn btn-primary"
            = link_to "Отмена", '', class: "cancel_form_link  btn-primary right_btn btn btn-default"

          /.row.row_comment  style = "display: inline-block; width: 900px"

   

app/views/questions/_question_row.html.slim
th  =link_to "Показать", question_path(question)
-if current_user && (current_user.id == question.user_id) 
  th  =link_to "Удалить", question_path(question), method: :delete, data: { confirm: "Удалить?" }
  th  =link_to "Исправить", edit_question_path(question)
tr
  td = question.title
  td colspan=2 = question.body

app/views/questions/edit.html.slim
title Редактировать вопрос

h4 Редактировать вопрос
   

div.row
  div.col-md-6.col-md-offset-3
    =form_for(@question, method: :patch) do |f| 
      .row
        .col-md-2
          =>f.label :Заголовок
        .col-md-6
          =f.text_field :title
      .row
        .col-md-2
          =f.label :Вопрос
        .col-md-6
          =f.text_field :body 

      .row.col-md-2 Attachments:
      .row
        .col-md-0
          = f.fields_for :attachments do |a|
            = render 'attachment_field_edit', f: a
        .col-md-10
          = link_to_add_association "Добавить", f, :attachments 
      
      .row 
        .col-md-0
      
          =>f.submit "Запомнить", class: "btn btn-primary"
          = link_to "Отмена", questions_path, 
           class: "cancel_form_link btn btn-default right_btn btn btn-primary"
            / pull-right 

app/views/questions/index.html.slim
    title Список вопросов
    h4 Список вопросов 

    .row 
      .col-md-0
        =>link_to "Создать вопрос", new_question_path, 
          class: "btn btn-primary newQuestionLink"  
          /if can?(:create, Question)   #CanCan
          
        =link_to "Выйти из программы","https://www.google.com/" , 
        class: "cancel_form_link btn btn-default right_btn btn btn-primary"

    - unless @questions.empty?
      table class="questions_table"
        - for question in @questions do
          = render 'question_row', question: question
    - else
      p Список вопросов пуст

app/views/questions/new.html.slim
title Создание вопроса

h4 Создание вопроса
   

div.row
  div.col-md-6.col-md-offset-3
    =form_for(@question,  method: :post) do |f| 
      .row
        .col-md-2
          =>f.label(:title, 'Заголовок')
        .col-md-6
          =f.text_field :title
      .row
        .col-md-2
          =f.label(:body, 'Вопрос') 
        .col-md-6
          =f.text_field :body 
      
      .row.col-md-2 Attachments:
      .row
        .col-md-0
          = f.fields_for :attachments do |a|
            = render 'attachment_fields', f: a
        .col-md-10
          = link_to_add_association "Добавить", f, :attachments 
      .row 
        .col-md-0
          =>f.submit "Запомнить", class: "btn btn-primary"
          = link_to "Отмена", questions_path,
           class: "cancel_form_link btn btn-default right_btn btn btn-primary"

app/views/questions/show.html.slim
    head
      meta http-equiv="Content-Type" content="text/html; charset=utf-8" 

    title Текущий вопрос и ответы
    h4 Текущий вопрос и ответы

    - attachments =@attachments


    h5 = "#{@question.title}   #{@question.body}"
    .answer-errors
    p Attachments:
    ul
      - @question.attachments.each do |a|
        li= link_to a.file.identifier, a.file.url
        /li= a.file.file.filename
        /li= link_to a.file.file.filename, a.file.url
        
    .row 
      .col-md-3

        = link_to "Возврат", questions_path, 
            class: "cancel_form_link btn btn-default right_btn btn btn-primary"

    - unless @question.comments.empty?
      p Комментарии:
      .comments_block
        - for comment in @question.comments do
          - if comment.persisted?
            = render 'comment_row', comment: comment
    - else
      p Список комментариев пуст

    br
    br
    -if user_signed_in?       
      button.btn.btn-primary.new_comment Создать комментарий
      .comment_container
        =form_for(@comment, url: question_comments_path(@comment.commentable),  method: :post) do |f| 
      
          .row
            .col-md-2
              =>f.label(:strComment, 'Комментарий') 
          .comment-errors
              =f.text_field :strComment 
          .row
            .col-md-2
              =>f.submit "Запомнить", class: "btn btn-primary"
              = link_to "Отмена", '',
               class: "cancel_form_link btn btn-default right_btn btn btn-primary"

    br
    - unless @question.answers.empty?
      p Ответы:
      table.answers_table 
        - for answer in @question.answers.order(best: :desc) do
          = render 'answer_row', answer: answer
    - else
      p Список ответов пуст

    br
    br

      /=>link_to "Создать ответ", new_question_answer_path(@question), 
           class: "btn btn-primary"  , id: "aaa"
       /(style="display:none")
    -if user_signed_in?       
      button.btn.btn-primary.aaa Создать ответ
      .answers_container
        - remote_sign = @question.answers.count > 0 ? true : false
        - format_sign = @question.answers.count > 0 ? :json : :html
        =form_for(@answer, url: question_answers_path(@answer.question, format: format_sign),  method: :post, remote: remote_sign) do |f| 
      
          .row
            .col-md-2
              =>f.label(:body, 'Ответ') 
          .answer-errors
            
              =f.text_field :body 
          .row
            .col-md-2
              =>f.label(:best, "Лучший")
          
              =>f.check_box(:best, {}, "true", "false")
          .row.col-md-2 Attachments:
          br
          .row
            .col-md-0
              = f.fields_for :attachments do |a|
                = render 'attachment_fields', f: a
            .col-md-10= link_to_add_association "Добавить", f, :attachments 
          
          .row
            .col-md-2
              =>f.submit "Запомнить", class: "btn btn-primary"
              = link_to "Отмена", '',
               class: "cancel_form_link btn btn-default right_btn btn btn-primary"