config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  authenticate :user, lambda {|u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end  
  use_doorkeeper
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :questions  do
    resources :comments, shallow: true,  defaults: { commentable: "question" }
    resources :answers, shallow: true do
      resources :comments, shallow: true, defaults: { commentable: "answer" }
    end
    resource :subscription, only: [:create, :destroy]
  end

  namespace :api do
    namespace :v1 do
     resources :profiles, only: [:index] do
      get :me, on: :collection 
     end
     resources :questions do 
        resources :answers, shallow: true
     end   
    end  
  end

  root to: "questions#index"
  
  get "users/add_email_form", to: "users#add_email_form", as: :add_email_form
  post "users/add_email", to: "users#add_email", as: :add_user_email

  get "search/", to: "search#index", as: :search
  get '/answers/new(.:format)', to: 'answers#new', as: 'new_answer'
#  get '/users/sign_up(.:format)', to: 'devise/registrations#new', as: 'new_user'
 mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  
    validates :question_id, :body, presence: true
    belongs_to :question, touch: true
    #, foreign_key: "question_id"
    has_many :attachments, as: :attachmentable
    accepts_nested_attributes_for :attachments, allow_destroy: true

    has_many :comments, as: :commentable
   # accepts_nested_attributes_for :comments, allow_destroy: true

    belongs_to :user
    
    default_scope { order(best: :desc, created_at: :desc) }

     after_create :new_answers_subscription


  private

   def new_answers_subscription
     NewAnswerJob.perform_later(self)
   end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :load_answer, only: [:show, :edit, :update, :destroy ]
    after_action  :publish_answer, only: [:create]
    

    #before_action :load_question, only: [:show, :edit, :update ]

    def index
      authorize @answer = Answer.all
      @answers = Answer.all
    end

    def show
      authorize @answer
      @answer = Answer.find_by(id: params[:id])
      @question = Question.find_by(id: @answer.question_id)
      @answer.attachments.build
      @answer.comments.build
      @comment = @answer.comments.new(user_id: current_user&.id)
      @comments = @answer.comments 
    end

    def edit
      authorize @answer
      #binding.pry
    end

    def create
      # @answer = Answer.new(answer_params.merge(question_id: params[:question_id]))
    
      @question = Question.find_by(id: params[:question_id])

      @answer = Answer.new(answer_params)
      @answer.question_id = params[:question_id]
      @answer.user_id = current_user.id
      @answers = @question.answers 
      authorize @answer
      if @answer.save
        @attachments =  @answer.attachments
  
          respond_to do |format|
            #format.html {  render partial: 'questions/answer_row', locals: { answer: @answer},  layout: false }
            format.html { redirect_to question_path(@question) }
          # format.json {  render json: @answer }
            format.json { render json: @answer.attributes.merge({ files: @attachments }), status: :created, location:  @answer }
          end
        
        else  
        #flash.notice = "Your answer invalid."

          respond_to do |format|
            format.html { redirect_to question_path(@question)  }
            format.json { render json: @answer.errors, status: :unprocessable_entity }
          end
      end  
    

      # if  @answer.save 
      #   # binding.pry
      #   # redirect_to action: :index
      #   redirect_to question_path(@answer.question)
      #   flash.notice = "Your answer successfully created."
      # else
      #   render :new  
      # end
    end

    def update
      authorize @answer
      @answer = Answer.find(params[:id])
      @answer.update(answer_params)
      #  puts '1----------------'
      #  puts params
      #  puts answer_params

      # if @answer.update(answer_params)
      #   puts '2----------------'
      #   puts params
      #   puts answer_params
      #    # redirect_to question_path(@answer.question)
      # else
      #   render :edit
      # end  
    end

  def destroy
    authorize @answer
    #@question = @answer.question
    if @answer.user_id == current_user.id
      @answer_id = @answer.id if @answer.destroy
    end
    #else
    #  flash.notice = "У Вас нет прав на удаление этой записи"
    #end  
    #redirect_to question_path(@question)
  end
  


    private

    def answer_params
      #  puts '---------------------'
      #  puts params
        params.require(:answer).permit(
          :body, 
          :best, 
          :question_id,
          attachments_attributes: [
            :file, 
            :attachmentable_id, 
            :attachmentable_type,
            :_destroy, :id ],
          comments_attributes: [
            :strComment, 
            :commentable_id, 
            :commentable_type,
            :_destroy, :id ]
        )
    end

  def load_answer
    @answer = Answer.find_by(id: params[:id])
  end

  def publish_answer
    return if @answer.errors.any?
    #ActionCable.server.broadcast('answers',  {text: 'new answer' })

    ActionCable.server.broadcast(
     'answers', 
     ApplicationController.render(
       partial: 'questions/answer_row',
       locals: { answer: @answer, current_user: current_user }
     )
   )
  end  

end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController

    before_action :find_question, only: [:index, :create]
    before_action :find_answer, only: [:show]
  
    #authorize_resource
  
    def index
      @answers = @question.answers
      respond_with @answers
    end
  
    def show
      respond_with @answer
    end
  
    def create
      respond_with (@answer = @question.answers.create(answer_params.merge(user_id: current_resource_owner.id)))
    end
  
    private
  
    def answer_params
      params.require(:answer).permit(:body)
    end
  
    def find_question
      @question = Question.find(params[:question_id])
    end
  
    def find_answer
      @answer = Answer.find(params[:id])
    end
  
  end
  

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_attachment_fields.html.slim
.row
.stroka_faila
  .nested-fields
    .field
      .row
      .col-md-1 => f.label :file
      .col-md-2 => link_to_remove_association 'Удалить', f
      .col-md-4 => f.file_field  :file||f.object.file.identifier
      - if f.object.file.present?
        .col-md-4 = f.object.file.identifier 
       

      
        

app/views/answers/create.js.erb
 console.log("<%= params['id'] %>")
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message|  %>

        $('.answer-errors').innerHTML ='<%= j message %>';
    <% end %>
<% else %>
    var tabl = document.querySelector('.answers_table');
    var last_row = document.createElement('tr');
    last_row.innerHTML = "<%= j render 'questions/answer_row', answer: @answer %>";
    tabl.appendChild(last_row);
    <% $('#answer_body').val(''); %>
    <% $('#answer_body').val(false); %>
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
     <% @answer.errors.full_messages.each do |message|  %>
    document.querySelector(".answer-errors").innerHTML = "<div><%= j message %></div>";
    <% end %>
<% else %>
   var tabl = document.querySelector('.answers_table');
   var current_row = document.querySelector(".answer_row_<%= @answer_id.to_s %>");
   current_row.remove();
 <% end %>
 
 //console.log("<%= params['id'] %>")

app/views/answers/edit.html.slim
h4 Редактирование ответа
div.row
  div.col-md-6.col-md-offset-3
    =form_for(@answer,  method: :patch) do |f| 
      .row
        .col-md-2
          =f.label(:body, "Ответ")
        .col-md-3
          =f.text_area :body 
      
      .row 
        .col-md-2
          =>f.submit "Сохранить", class: "btn-primary btn"
            /.col-md-8
          =link_to "Отмена", question_path(@answer.question), 
            class: "cancel_form_link  btn-primary right_btn btn btn-default"
              /  pull-right 

app/views/answers/new.html.slim
h4 Создание ответа
div.row
  div.col-md-6.col-md-offset-3
    =form_for(@answer, url: question_answers_path(@answer.question),  method: :post) do |f| 
      .row
        .col-md-2
          =f.label :Ответ
        .col-md-3
          =f.text_field :body 
      
      .row 
        .col-md-3
      
          =>f.submit "Запомнить", class: "btn btn-primary"
            / .col-md-4
          = link_to "Отмена",  question_path(@answer.question), class: "cancel_form_link btn btn-default right_btn btn-primary"
          /  pull-right 

app/views/answers/show.html.slim
title Текущий ответ и комментарии
h4 Текущий ответ и комментарии

h5 = "#{@answer.body}"
.comment-errors

.row 
  .col-md-12
    = link_to "Возврат", question_path(@answer.question), 
        class: "cancel_form_link btn btn-default right_btn btn btn-primary"

    - unless @answer.comments.empty?
      p Комментарии:
      .row
        .col-md-12
          - for comment in @answer.comments do
            - if comment.persisted?
              = render 'questions/comment_row', comment: comment
    - else
      p Список комментариев пуст

    br
    br
    -if user_signed_in?       
      button.btn.btn-primary.new_comment Создать комментарий
      .comment_container
        =form_for(@comment, url: answer_comments_path(@comment.commentable),  method: :post) do |f| 
      
          .row
            .col-md-2
              =>f.label(:strComment, 'Комментарий') 
          .comment-errors
              =f.text_field :strComment 
          .row
            .col-md-2
              =>f.submit "Запомнить", class: "btn btn-primary"
              = link_to "Отмена", '',
               class: "cancel_form_link btn btn-default right_btn btn btn-primary"

/  .col-md-6.col-md-offset-3
   

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message|  %>
    document.querySelector(".answer-errors").innerHTML = "<div><%= j message %></div>";
    <% end %>
<% else %>
   var current_row = document.querySelector(".answer_row_<%= @answer.id.to_s %>");
   current_row.innerHTML = "<%= j render 'questions/answer_row', answer: @answer %>";
<% end %>